<div id="main">
    <!--breadcrumb-section starts-->
    <div class="breadcrumb-section">
        <div class="container">
            <h1>Групна настава</h1>
            <div class="breadcrumb">
                <a href="<?= $this->baseUrl('/');?>">Почетна</a>
                <span class="fa fa-angle-double-right"></span>
                <a href="shortcodes.html">Настава</a>
                <span class="fa fa-angle-double-right"></span>
                <span class="current">Групна настава</span>
            </div>
        </div>
    </div>
    <!--breadcrumb-section ends-->
    <!--container starts-->
    <div class="container">
        <!--primary starts-->
        <section id="primary" class="content-full-width">
            <br>
            <h2 class="dt-sc-hr-green-title">Подразумева рад у малим групама, до 6 полазника. <br> У зависности од узраста, одржава се у три категорије:</h2>
            <br>
            <div class="column dt-sc-one-column">
                <img src="http://wedesignthemes.com/html/kidslife/images/blog_img1.jpg" style="height: 200px; width: 96%;">
            </div>
            <div class="dt-sc-hr-medium"></div>
            <div class="dt-sc-hr-medium"></div>
            <div class="column dt-sc-one-third first">
                <div class="dt-sc-ico-content type3">
                    <div class="icon">
                        <span class="fa fa-puzzle-piece"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Креативне радионице </a></h4>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>
                </div>
            </div>

            <div class="column dt-sc-one-third">
                <div class="dt-sc-ico-content type3">
                    <div class="icon">
                        <span class="fa fa-bell"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Мали оркестар </a></h4>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>                </div>
            </div>

            <div class="column dt-sc-one-third">
                <div class="dt-sc-ico-content type3">
                    <div class="icon">
                        <span class="fa fa-smile-o"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Хорић </a></h4>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>
                    <p>Nunc at pretium est curabitur commodo leac est venenatis egestas sed aliquet auguevelit. Curabitur vulputate, ligula lacinia scelerisque</p>                </div>
            </div>
            <div class="dt-sc-hr-medium"></div>
        </section>
        <!--primary ends-->
    </div>
    <!--container ends-->
</div>