<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img-courses" style="background-position: 50% -79px;">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">РАДИОНИЦЕ</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">ИЗБОР РАДИОНИЦЕ</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space60"></div>
                <div class="nicdark_space50"></div>
            </div>

        </div>
        <!--end nicdark_container-->

    </div>
     
</section>

<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">


        <div class="nicdark_space50"></div>


        <a href="<?= $this->url(array(), 'workshopindividual', true);?>">
            <div class="grid grid_6">
                <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                    <div style="" class="nicdark_archive1 nicdark_radius">
                        <div class="nicdark_filter orange nicdark_radius_top">
                            <div class="nicdark_space60"></div>
                                <h4 class="white nicdark_margin20">ИНДИВИДУАЛНА НАСТАВА</h4>
                            <div class="nicdark_space60"></div>
                        </div>
                    </div>
                </div>
            </div>
        </a>

        <a href="<?= $this->url(array(), 'workshopgroup', true);?>">
            <div class="grid grid_6">
                <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                    <div style="" class="nicdark_archive1 nicdark_radius">
                        <div class="nicdark_filter yellow nicdark_radius_top">
                            <div class="nicdark_space60"></div>
                                <h4 class="white nicdark_margin20">ГРУПНА НАСТАВА</h4>
                            <div class="nicdark_space60"></div>
                        </div>
                    </div>
                </div>
            </div>
        </a>

    </div>
    <div class="nicdark_space20"></div>
    <!--end nicdark_container-->
            
</section>