<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img-courses" style="background-position: 50% -79px;">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">РАДИОНИЦЕ</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">ЛИСТА СВИХ РАДИОНИЦА</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space60"></div>
                <div class="nicdark_space50"></div>
            </div>

        </div>
        <!--end nicdark_container-->

    </div>
     
</section>

<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">


        <div class="nicdark_space50"></div>


        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/courses/img3.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter orange nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">КЛАВИР</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt rutrum sapien, sed ultricies diam condimentum nec. Morbi a commodo neque, sit amet tempor arcu..</p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_orange medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>

        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/courses/img2.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter yellow nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">СОЛФЕЂО</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Mоже бити „баук“ многима то обично и јесте, због неразумевања и страха у почетку учења. 
                        Обично се учи на групној настави, па је самим тим теже да се професор посвети...</p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_yellow medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>

        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/courses/img1.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter green nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">СОЛО ПЕВАЊЕ</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Учимо технике дисања и основе соло-певачке, вокалне, технике. Научите најлепше песме старих 
                        мајстора и домаћих аутора. Држимо и припремну наставу за упис у нижу...</p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_blue medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>

        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/excursions/img8.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter blue nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">ПОПУЛАРНА И ЏЕЗ МУЗИКА</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Волите да певате, али бисте волели да своје певање мало „уобличите“ и научите неке од цака којима 
                        се служе популарне звезде данашњице? Да проширите распон гласа и... </p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_blue medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>

        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/excursions/img1.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter blue nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">УВОД У КОМПОНОВАЊЕ</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Jе програм за ученике за које се подразумева да познају основе теорије музике и солфеђа.
                    Научите да уобличите и запишете своје идеје и створите чаробне мелодије!</p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_blue medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>

        <div class="grid grid_4">
            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                <div style="background:url(img/excursions/img6.jpg); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                    <div class="nicdark_filter violet nicdark_radius_top">
                        <div class="nicdark_space60"></div>
                        <div class="nicdark_space60"></div>
                    </div>
                </div>
                <div class="nicdark_textevidence nicdark_bg_greydark">
                    <h4 class="white nicdark_margin20">ОСНОВЕ ТЕОРИЈЕ МУЗИКЕ</h4>
                </div>
                <div class="nicdark_margin20">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt rutrum sapien, sed ultricies diam condimentum nec. Morbi a commodo neque, sit amet tempor arcu..</p>
                    <div class="nicdark_space20"></div>
                    <a href="single-course.html" class="white nicdark_btn nicdark_bg_violet medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                </div>
            </div>
        </div>
    </div>
    <div class="nicdark_space20"></div>
    <!--end nicdark_container-->
            
</section>