<div id="main">
    <!--breadcrumb-section starts-->
    <div class="breadcrumb-section">
        <div class="container">
            <h1>Радионице</h1>
            <div class="breadcrumb">
                <a href="<?= $this->baseUrl('/');?>">Почетна</a>
                <span class="fa fa-angle-double-right"></span>
                <span class="current">Радионице</span>
            </div>
        </div>
    </div>
    <!--breadcrumb-section ends-->
    <!--container starts-->
    <div class="container">
        <!--primary starts-->
        <section id="primary" class="content-full-width">
            <div class="column dt-sc-one">
                <style>blockquote q:before{display: none;}blockquote q:after{display: none;}</style>
                <blockquote class="burnt-orange">
                    <q>Свака радионица је намењена одређеном узрасту и има своју тему, 
                    то јест кроз различите радионице, учићемо различите занимљиве садржаје. 
                    Радионице су намењене најмлађим полазницима, почевши од 3 године. 
                    У зависности од броја и узраста пријављене деце, формирамо групе.</q>                        
                </blockquote>
            </div>

            <h2 class="dt-sc-hr-green-title" style="padding-top: 25px;"> Неке од радионица </h2>

            <div class="column dt-sc-one-fourth first">
                <div class="activity box1">
                        <h4> Звук </h4>
                    <img src="images/activity1.jpg" alt="" title="">
                    <p>Vestibulum Ante Ipsum Primis In Faucibus Orci Luctus Et Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>
                </div>
            </div>

            <div class="column dt-sc-one-fourth">
                <div class="activity box2">
                        <h4> Ритам </h4>
                    <img src="images/activity2.jpg" alt="" title="">
                    <p>Vestibulum Ante Ipsum Primis In Faucibus Orci Luctus Et Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>
                </div>
            </div>

            <div class="column dt-sc-one-fourth">
                <div class="activity box3">
                        <h4> Мелодија </h4>
                    <img src="images/activity3.jpg" alt="" title="">
                    <p>Vestibulum Ante Ipsum Primis In Faucibus Orci Luctus Et Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>
                </div>
            </div>

            <div class="column dt-sc-one-fourth">
                <div class="activity box4">
                        <h4> Музичке игре и бројалице </h4>
                    <img src="images/activity4.jpg" alt="" title="">
                    <p>Vestibulum Ante Ipsum Primis In Faucibus Orci Luctus Et Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>
                </div>
            </div>
            
            <div class="dt-sc-hr" style="margin-top: 5px;"></div>
            
            <div class="column dt-sc-one-fourth"><p></p></div>
            <div class="column dt-sc-one-fourth first">
                <div class="activity box4">
                        <h4> Учење нота уз помоћ шарених картица</h4>
                    <img src="images/blog_img2.jpg" alt="" title="">
                    <p>Curabitur vulputate, ligula lacinia scelerisque tempor, 
                        lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>                
                </div>
            </div>
            <div class="column dt-sc-one-fourth">
                <div class="activity box1">
                        <h4> Уради сам-направи  свој инструмент! </h4>
                    <img src="images/blog_img6.jpg" alt="" title="">
                    <p>Curabitur vulputate, ligula lacinia scelerisque tempor, 
                        lacus lacus ornare ante, ac egestas est urna sit amet arcu</p>
                </div>
            </div>
            <div class="column dt-sc-one-fourth"><p></p></div>

            <div class="dt-sc-hr"></div>

            <div class="dt-sc-one-half column first">
                    	<h2>Датуми радионица</h2>  
                        <div class="events-list">
                            <div class="event-thumb">
                                <a href="#" title="">
                                	<img src="images/image8.jpg" class="" alt="" title="">
                                </a>
                            </div>
                            <div class="event-details">
                                <div class="event-meta">
                                	<span class="fa fa-calendar"> </span> 27 Септ 2016
                                </div>
                                <h2><a href="#">Наслов 1</a></h2>
                                <div class="event-excerpt">
                                    <p>Aenean lacinia sed diam eget risus varius ibendum nulla sed consectetur. Maecenas sed diam eget risus varius bla nditsed diam eget risus varius</p>
                                </div>
                            </div>
                        </div>
                        <div class="events-list">
                            <div class="event-thumb">
                                <a href="#" title="">
                                	<img src="images/image9.jpg" class="" alt="" title="">
                                </a>
                            </div>
                            <div class="event-details">
                                <div class="event-meta">
                                	<span class="fa fa-calendar"> </span> 27 Септ 2016
                                </div>
                                <h2><a href="#">Наслов 2</a></h2>
                                <div class="event-excerpt">
                                    <p>Aenean lacinia sed diam eget risus varius ibendum nulla sed consectetur. Maecenas sed diam eget risus varius bla nditsed diam eget risus varius</p>
                                </div>
                            </div>
                        </div>
                        <div class="events-list">
                            <div class="event-thumb">
                                <a href="#" title="">
                                	<img src="images/image10.jpg" class="" alt="" title="">
                                </a>
                            </div>
                            <div class="event-details">
                                <div class="event-meta">
                                	<span class="fa fa-calendar"> </span> 27 Септ 2016
                                </div>
                                <h2><a href="#">Наслов 3</a></h2>
                                <div class="event-excerpt">
                                    <p>Aenean lacinia sed diam eget risus varius ibendum nulla sed consectetur. Maecenas sed diam eget risus varius bla nditsed diam eget risus varius</p>
                                </div>
                            </div>
                        </div>
                    </div>

            <!--dt-sc-one-half starts-->
            <div class="dt-sc-one-half column">
                    <h2>Мали Моцарт Музика</h2>
                    <p>Музика креирана од руку наших најмлађих полазника.</p>
                        <iframe width="572" height="120" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/153425116&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
                        <div class="dt-sc-hr-small"></div>
                        <iframe width="572" height="120" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/135808424&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
                        <div class="dt-sc-hr-small"></div>
                        <iframe width="572" height="120" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/2902567&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
            </div>
            <!--dt-sc-one-half ends-->
            <div class="dt-sc-hr"></div>
        </section>
        <!--primary ends-->
    </div>
    <!--container ends-->
</div>