<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img-courses" style="background-position: 50% -79px;">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">НАСТАВА</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">ИНДИВИДУАЛНА</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space60"></div>
                <div class="nicdark_space50"></div>
            </div>
        </div>
        <!--end nicdark_container-->
    </div>
</section>
<!-- MODAL BOXES -->
    <?php foreach ($this->workshopindividual as $workshop):?>
        <div id="<?= $workshop['id'];?>" style="display:none;">
          <p style="color: #fff; font-size: 17px;text-align: center;"><?= $workshop['title'];?>
              <br><?= $workshop['description'];?></p>
        </div>
    <?php endforeach; ?>

<!-- END MODAL BOXES -->
<section class="nicdark_section">
    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">
        <div class="nicdark_space50"></div>
        <?php $colorArray = array('blue', 'orange', 'green','yellow','red',);?>
        <?php foreach ($this->workshopindividual as $workshop):?>
                <div class="grid grid_4">
                    <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow center"> 
                        <div style="background:url(<?= $this->workshopImgUrl($workshop);?>); background-size:cover;" class="nicdark_archive1 nicdark_radius">
                            <div class="nicdark_filter  <?= $colorArray[array_rand($colorArray)]; ?> nicdark_radius_top">
                                <div class="nicdark_space60"></div>
                                <div class="nicdark_space60"></div>
                            </div>
                        </div>
                        <div class="nicdark_textevidence nicdark_bg_greydark">
                            <h4 class="white nicdark_margin20"><?= strtoupper($workshop['title']);?></h4>
                        </div>
                        <div class="nicdark_margin20">
                            <p><?= $workshop['short_description'];?></p>
                            <div class="nicdark_space20"></div>
                            <a href="#<?= $workshop['id'];?>" rel="modal:open" class="white nicdark_btn nicdark_bg_orange medium nicdark_radius nicdark_shadow nicdark_press">ДЕТАЉНИЈЕ</a>
                        </div>
                    </div>
                </div>
        <?php endforeach; ?>

    </div>
    <div class="nicdark_space20"></div>
    <!--end nicdark_container-->
            
</section>