<div id="main">
    <!--breadcrumb-section starts-->
    <div class="breadcrumb-section">
        <div class="container">
            <h1>Индивидуална настава</h1>
            <div class="breadcrumb">
                <a href="<?= $this->baseUrl('/');?>">Почетна</a>
                <span class="fa fa-angle-double-right"></span>
                <a href="shortcodes.html">Настава</a>
                <span class="fa fa-angle-double-right"></span>
                <span class="current">Индивидуална настава</span>
            </div>
        </div>
    </div>
    <!--breadcrumb-section ends-->
    <!--container starts-->
    <div class="container">
        <!--primary starts-->
        <section id="primary" class="content-full-width">

            <h2 class="dt-sc-hr-green-title">Индивидуална настава</h2>

            <!--dt-sc-one-half starts-->
            <div class="dt-sc-one-half column first">

                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Клавир </a></h4>
                    <p>Nam ullamcorper, diam sit amet euismod pelleontesque, eros risus rhoncus libero, inst tibulum nisl ligula....</p>
                </div>
                <div class="dt-sc-hr-very-small"></div>
                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Солфеђо </a></h4>
                    <p>Солфеђо може бити „баук“ многима то обично и јесте, због неразумевања и страха у почетку учења.
                        Обично се учи на групној настави, па је самим тим теже да се професор посвети сваком појединачно,
                        а такође изискује и редовно вежбање код куће.
                        Ми смо ту да Вам помогнемо када негде „зашкрипи“.
                    </p>
                </div>
                <div class="dt-sc-hr-very-small"></div>
                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Соло певање </a></h4>
                    <p>Nam ullamcorper, diam sit amet euismod pelleontesque, eros risus rhoncus libero, inst tibulum nisl ligula....</p>
                </div>

            </div>
            <!--dt-sc-one-half ends-->

            <!--dt-sc-one-half starts-->
            <div class="dt-sc-one-half column">

                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Популарна и џез музика-певање </a></h4>
                    <p>Nam ullamcorper, diam sit amet euismod pelleontesque, eros risus rhoncus libero, inst tibulum nisl ligula....</p>
                </div>
                <div class="dt-sc-hr-very-small"></div>
                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Увод у комповање  </a></h4>
                    <p>Nam ullamcorper, diam sit amet euismod pelleontesque, eros risus rhoncus libero, inst tibulum nisl ligula....</p>
                </div>
                <div class="dt-sc-hr-very-small"></div>
                <div class="dt-sc-ico-content type2">
                    <div class="icon">
                        <span class="fa fa-circle"> </span>
                    </div>
                    <h4><a href="#" target="_blank"> Основе теорије музике </a></h4>
                    <p>Nam ullamcorper, diam sit amet euismod pelleontesque, eros risus rhoncus libero, inst tibulum nisl ligula....</p>
                </div>

            </div>
            <!--dt-sc-one-half ends-->
            <div class="dt-sc-hr-medium"></div>
            <div class="dt-sc-hr-medium"></div>
        </section>
        <!--primary ends-->
    </div>
    <!--container ends-->
</div>


