<!--start section-->
<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img5">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">ПРИЈАВА</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">ПРИЈАВИТЕ СЕ И ОСТВАРИТЕ ПОПУСТ!</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space40"></div>
                <div class="nicdark_space50"></div>
            </div>

        </div>
        <!--end nicdark_container-->

    </div>
     
</section>
<!--end section-->


<!--start section-->
<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space40"></div>

        <div class="grid grid_6">
            <!--title-->
            <h3 class="subtitle greydark">ФОРМА ЗА ПРИЈАВУ</h3>
            <div class="nicdark_space20"></div>
            <div class="nicdark_divider left small"><span class="nicdark_bg_yellow nicdark_radius"></span></div>
            <!--title--> 
            
            <div class="nicdark_space20"></div>

            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                <div class="nicdark_textevidence nicdark_bg_yellow nicdark_radius_top">
                    <h4 class="white nicdark_margin20">ВАШЕ ИНФОРМАЦИЈЕ</h4>
                    <i class="icon-globe-1 nicdark_iconbg right medium yellow"></i>
                </div>
                <div class="nicdark_margin20">
                    <p>ИМЕ РОДИТЕЉА:</p>
                    <div class="nicdark_space5"></div>
                    <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" type="text" value="" size="200">
                    <div class="nicdark_space20"></div>
                    <p>ПРЕЗИМЕ РОДИТЕЉА:</p>
                    <div class="nicdark_space5"></div>
                    <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" type="text" value="" size="200">
                    <div class="nicdark_space20"></div>
                    <p>ИМЕ И ПРЕЗИМЕ ДЕТЕТА:</p>
                    <div class="nicdark_space5"></div>
                    <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" type="text" value="" size="200">
                    <div class="nicdark_space20"></div>
                    <p>И-МЕЈЛ:</p>
                    <div class="nicdark_space5"></div>
                    <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" type="text" value="" size="200">
                    <div class="nicdark_space20"></div>
                    <p>ТЕЛЕФОН:</p>
                    <div class="nicdark_space5"></div>
                    <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" type="text" value="" size="200">
                    <div class="nicdark_space20"></div>
                    <input class="nicdark_btn nicdark_bg_yellow medium nicdark_shadow nicdark_radius white nicdark_press" type="submit" value="ПОТВРДИ">
                </div>
            </div>

        </div>
        
       <div class="grid grid_6">
           <div class="nicdark_space60" style="margin-top: -8px;"></div>
            <div class="grid grid_6">
                <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                    <div class="nicdark_textevidence nicdark_bg_yellow nicdark_radius_top">
                        <h4 class="white nicdark_margin20">ФОРМА ЗА ПРИЈАВУ</h4>
                        <i class="icon-text-width nicdark_iconbg right medium yellow"></i>
                    </div>
                    <div class="nicdark_margin20">
                        <p>Попуњавањем ове пријаве дајете нам до знања да сте заинтересовани за неки од наших програма, чиме нам омогућавате
                        бољу организацију и увид у број заинтересованих, као и формирање група. Слободно нас контактирајте за сва питања и информације!
                        </p>
                        <div class="nicdark_space20"></div>
                    </div>
                </div>
            </div>
           
            <div class="grid grid_6">
                 <div class="nicdark_calendar"></div>
            </div>
        </div>
    </div>
    <!--end nicdark_container-->
    <div class="nicdark_space50"></div>
</section>
<!--end section-->