<div id="main">
            <?php echo $this->indexSlider(); ?>
            <!--primary starts-->
            <section id="primary" class="content-full-width">
                <!--container starts-->
                <div class="container">
                    
                    <div class="dt-sc-one-fourth column first">
                        <div class="dt-sc-ico-content type1">
                            <div class="icon">
                                <span class="icon-outer">
                                    <img src="images/service1.jpg" alt="" title="">
                                    <span class="infolayer">
                                        <a href="<?= $this->url(array('controller' => 'about', 'action' => 'index'),'default', true) ?>">
                                            <i class="fa fa-link">
                                            </i>
                                        </a>
                                    </span>
                                </span>
                            </div>
                            <h4><a href="<?= $this->url(array('controller' => 'about', 'action' => 'index'),'default', true) ?>">
                                    О Нама
                                </a>
                            </h4>
                            <p>Музички студио, или како га ми радије зовемо- ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“, отворен је са циљем да кроз занимљиве интерактивне садржаје и програме приближи и објасни музику...  
                                <a href="<?= $this->url(array('controller' => 'about', 'action' => 'index'),'default', true) ?>"> детаљније</a></p>
                        </div>
                    </div>
                    
                    <div class="dt-sc-one-fourth column">
                        <div class="dt-sc-ico-content type1">
                            <div class="icon">
                                <span class="icon-outer">
                                    <img src="images/service2.jpg" alt="" title="">
                                    <span class="infolayer">
                                        <a href="<?= $this->url(array('controller' => 'workshop', 'action' => 'index'),'default', true) ?>">
                                            <i class="fa fa-link">
                                            </i>
                                        </a>
                                    </span>
                                </span>
                            </div>
                            <h4><a href="<?= $this->url(array('controller' => 'workshop', 'action' => 'index'),'default', true) ?>">
                                    Музичке радионице
                                </a>
                            </h4>
                            <p>Свака радионица је намењена одређеном узрасту и има своју тему, то јест кроз различите радионице, учићемо различите занимљиве садржаје. Радионице су намењене најмлађим полазницима.... 
                                <a href="<?= $this->url(array('controller' => 'workshop', 'action' => 'index'),'default', true) ?>">детаљније</a></p>
                        </div>
                    </div>
                    
                    <div class="dt-sc-one-fourth column">
                        <div class="dt-sc-ico-content type1">
                            <div class="icon">
                                <span class="icon-outer">
                                    <img src="images/service3.jpg" alt="" title="">
                                    <span class="infolayer">
                                        <a href="<?= $this->url(array('controller' => 'school', 'action' => 'index'),'default', true) ?>">
                                            <i class="fa fa-link">
                                            </i>
                                        </a>
                                    </span>
                                </span>
                            </div>
                            <h4><a href="<?= $this->url(array('controller' => 'school', 'action' => 'index'),'default', true) ?>">
                                    Настава
                                </a>
                            </h4>
                            <p>Индивидуални и групни часови клавира, солфеђа, теорије музике, соло певања, популарна и филмска музика, увод у компоновање, мали хор, мали оркестар… 
                                <a href="<?= $this->url(array('controller' => 'school', 'action' => 'index'),'default', true) ?>">детаљније</a></p>
                        </div>
                    </div>
                    
                    <div class="dt-sc-one-fourth column">
                        <div class="dt-sc-ico-content type1">
                            <div class="icon">
                                <span class="icon-outer">
                                    <img src="images/service4.jpg" alt="" title="">
                                    <span class="infolayer">
                                        <a href="<?= $this->url(array('controller' => 'teachers', 'action' => 'index'),'default', true) ?>">
                                            <i class="fa fa-link">
                                            </i>
                                        </a>
                                    </span>
                                </span>
                            </div>
                            <h4><a href="<?= $this->url(array('controller' => 'teachers', 'action' => 'index'),'default', true) ?>">
                                    Предавачи
                                </a>
                            </h4>
                            <p>Наш стручни тим чини група младих дипломаца и мастера Музичке Академије, са великим досадашњним искуством у раду са најмлађима. Рад по светски признатим методама.... 
                                <a href="<?= $this->url(array('controller' => 'teachers', 'action' => 'index'),'default', true) ?>">детаљније</a></p>
                        </div>
                    </div>
                </div>
                
                <div class="dt-sc-hr"></div>

            </section>
            <!--primary ends-->
        </div>