<?php
//disable layout
Zend_Layout::getMvcInstance()->disableLayout();

error_reporting(1); // Set E_ALL for debuging

// load composer autoload before load elFinder autoload If you need composer
//require APPLICATION_PATH . '/../vendor/autoload.php';

// elFinder autoload
//require APPLICATION_PATH . '/../vendor/autoload.php';

elFinder::$netDrivers['ftp'] = 'FTP';
// ===============================================


/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
	return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
		? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
		:  null;                                    // else elFinder decide it itself
}


// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => PUBLIC_PATH . '/uploads/filemanager', // path to files (REQUIRED)
			'URL'           => $this->baseUrl('/uploads/filemanager'), // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array(
                            'image', 
                            'text/plain', 
                            'application/pdf', 
                            'application/x-pdf'
                            ),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

