<?php
$this->headTitle('Датотеке');
?>
<section id="content_wrapper">
    <header id="topbar" class="alt">
       <div class="topbar-left">
          <ol class="breadcrumb">
             <li class="breadcrumb-link">
                <a href="<?= $this->url(array('controller' => 'admin_dashboard', 'action' => 'index'), 'default', true);?>">CMS Почетна</a>
             </li>
             <li class="breadcrumb-link">
                <a>Фајл менаџер</a>
             </li>
          </ol>
       </div>
    </header>
</section>
<div class="col-lg-12">
    <br><br>
    <?php echo $this->systemMessagesHtml($this->systemMessages);?>
</div>
<section id="content_wrapper">
<div id="content">
   <div class="panel panel-primary">
        <div class="panel-heading">
        <span class="panel-title pn"> </span>
        </div>
        <div class="panel-body" id="filemanager-container">
        </div>
    </div>
</div>
</section>
<?php 
//elFinder
$this->inlineScript()->appendFile($this->baseUrl('/admin/js/plugins/elfinder/js/elfinder.min.js'));
$this->headLink()->appendStylesheet($this->baseUrl('/admin/js/plugins/elfinder/css/elfinder.min.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/admin/js/plugins/elfinder/css/theme.css'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/js/plugins/elfinder/js/elfinder.min.js'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/js/plugins/elfinder/js/i18n/elfinder.sr.js'));
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
    $('#filemanager-container').elfinder({
        url: '<?php echo $this->url(array('controller' => 'admin_filemanager', 'action' => 'connector'), 'default', true) ;?>',
        lang : 'sr'
    });
<?php $this->inlineScript()->captureEnd(); ?>    
</script>