<section id="content_wrapper">
<header id="topbar" class="alt">
       <div class="topbar-left">
          <ol class="breadcrumb">
             <li class="breadcrumb-link">
                <a href="">CMS</a>
             </li>
             <li class="breadcrumb-current-item">Почетна</li>
          </ol>
       </div>
    </header>
    <div class="row mb10">
        <div class="col-sm-3 col-md-3">
           <div class="panel panel-tile text-dark light">
                <div class="panel-body pn pl20 p5">
                   <i class="fa fa-pencil-square-o icon-bg"></i>
                   <h2 class="mt15 lh15">
                      <b>5</b>
                   </h2>
                   <h5 class="text-muted">Објава</h5>
                </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-3">
            <div class="panel panel-tile text-primary br-b bw5 br-primary-light">
               <div class="panel-body pl20 p5">
                  <i class="fa fa-users icon-bg"></i>
                  <h2 class="mt15 lh15">
                     <b>45</b>
                  </h2>
                  <h5 class="text-muted">Пријављених</h5>
               </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-3">
            <div class="panel panel-tile bg-system light">
               <div class="panel-body pn pl20 p5">
                  <i class="fa fa-comment icon-bg"></i>
                  <h2 class="mt15 lh15 text-white">
                     <b>14</b>
                  </h2>
                  <h5 class="text-muted">Порука</h5>
               </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-3">
            <div class="panel panel-tile text-primary br-b bw5 br-primary-light">
               <div class="panel-body pl20 p5">
                  <i class="fa fa-bar-chart icon-bg"></i>
                  <h2 class="mt15 lh15">
                     <b>466</b>
                  </h2>
                  <h5 class="text-muted">Посета</h5>
               </div>
            </div>
        </div>
    </div> 
    <section id="content" class="table-layout animated fadeIn">
       <div class="chute chute-center">
          <div class="allcp-panels fade-onload">
              
          </div>
       </div>
    </section>
 </section>