<?php Zend_Layout::getMvcInstance()->disableLayout(); ?>
<head>
    <meta charset="utf-8">  
    <?php echo $this->headTitle('Школица Мали Моцарт')->setSeparator(' | ');?>
    <meta name="description" content="школица мали моцарт, опис неки."> 
    <meta name="author" content="djordjewebdizajn@gmail.com"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <?php echo $this->headMeta();?>
    <!--START CSS--> 
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/nicdark_style.css');?>"> <!--style-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/nicdark_responsive.css');?>"> <!--nicdark_responsive-->

    <!--revslider-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/revslider/settings.css');?>"> <!--revslider-->
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montez" rel="stylesheet" type="text/css">
    <?php echo $this->headStyle();?>
    <!--END CSS-->
    <?php echo $this->headScript();?>

    <!--[if lt IE 9]>  
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>  
    <![endif]-->  
    
    <!--FAVICONS-->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/img/favicon/favicon.ico');?>">
    <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon.png');?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon-72x72.png');?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon-114x114.png');?>">
    <!--END FAVICONS-->
    
</head>  
<body id="start_nicdark_framework" style="background-color: #495052;">
    
    <div class="mfp-content" style="width: 100%; top: 180px; margin: 0 auto;">
    <div id="nicdark_window">
    <div class="random">
    <div class="grid grid_4 nicdark_relative" style=" margin-bottom: 10px;">    
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
    <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
        <div class="nicdark_textevidence nicdark_bg_yellow nicdark_radius_top">
            <h4 class="white nicdark_margin20">ПРИСТУП ПАНЕЛУ</h4>
        </div>
        <div class="nicdark_margin20">
            <form method="POST" id="loginForm">
            <input type="hidden" name="task" value="login">
                <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" name="username" type="text"  placeholder="КОРИСНИЧКО ИМЕ">
                    <div class="nicdark_space20"></div>
                <input class="nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle" name="password" type="text"  placeholder="ЛОЗИНКА">
                    <div class="nicdark_space20"></div>
                <a class="nicdark_btn nicdark_bg_yellow medium nicdark_shadow nicdark_radius white nicdark_press" 
                   onclick='this.parentNode.submit(); return false;' type="submit">ПРИСТУП</a>
            </form>
        </div>
        </div>
    </div>
    </div>
</div>
</body>
    <!--main-->
    <script src="<?php echo $this->baseUrl('/js/main/jquery.min.js');?>"></script> <!--Jquery-->
    <script src="<?php echo $this->baseUrl('/js/main/jquery-ui.js');?>"></script> <!--Jquery UI-->
    <script src="<?php echo $this->baseUrl('/js/main/excanvas.js');?>"></script> <!--canvas need for ie-->

    <!--plugins-->
    <script src="<?php echo $this->baseUrl('/js/plugins/revslider/jquery.themepunch.tools.min.js');?>"></script> <!--revslider-->
    <script src="<?php echo $this->baseUrl('/js/plugins/revslider/jquery.themepunch.revolution.min.js');?>"></script> <!--revslider-->

    <!--menu-->
    <script src="<?php echo $this->baseUrl('/js/plugins/menu/superfish.min.js');?>"></script> <!--superfish-->
    <script src="<?php echo $this->baseUrl('/js/plugins/menu/tinynav.min.js');?>"></script> <!--tinynav-->

    <!--other-->
    <script src="<?php echo $this->baseUrl('/js/plugins/isotope/isotope.pkgd.min.js');?>"></script> <!--isotope-->
    <script src="<?php echo $this->baseUrl('/js/plugins/mpopup/jquery.magnific-popup.min.js');?>"></script> <!--mpopup-->
    <script src="<?php echo $this->baseUrl('/js/plugins/scroolto/scroolto.js');?>"></script> <!--Scrool To-->
    <script src="<?php echo $this->baseUrl('/js/plugins/nicescrool/jquery.nicescroll.min.js');?>"></script> <!--Nice Scroll-->
    <script src="<?php echo $this->baseUrl('/js/plugins/inview/jquery.inview.min.js');?>"></script> <!--inview-->
    <script src="<?php echo $this->baseUrl('/js/plugins/parallax/jquery.parallax-1.1.3.js');?>"></script> <!--parallax-->
    <script src="<?php echo $this->baseUrl('/js/plugins/countto/jquery.countTo.js');?>"></script> <!--jquery.countTo-->
    <script src="<?php echo $this->baseUrl('/js/plugins/countdown/jquery.countdown.js');?>"></script> <!--countdown-->
    
    <!--settings-->
    <script src="<?php echo $this->baseUrl('/js/settings.js');?>"></script> <!--settings-->