<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">  
    <?php echo $this->headTitle('Школица Мали Моцарт')->setSeparator(' | ');?>
    <meta name="description" content="Како име каже, ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“ ради управо то- кроз игру, покрет, визуелизацију, 
                цртање, плес и низ других активности, малишани активно учествују у радионицама, те упијају нове вештине, 
                развијају своје ритмичке, моторичке и музичке способности, као и музички језик (ноте, динамика, темпо итд) 
                на један леп, неоптерећујући начин."> 
    <meta name="author" content="Мали-Моцарт"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <?php echo $this->headMeta();?>
    <!--START CSS-->  
   <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/nicdark_style.css');?>"> <!--style-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/nicdark_responsive.css');?>"> <!--nicdark_responsive-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/jquery.modal.css');?>"> <!--revslider-->
    <!--revslider-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/revslider/settings.css');?>"> <!--revslider-->
    <link rel='stylesheet' id='layerslider-css' href="<?php echo $this->baseUrl('/css/layerslider.css')?>" type='text/css' media='all' />
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montez" rel="stylesheet" type="text/css">
    <?php echo $this->headStyle();?>
    <!--END CSS-->
    <?php echo $this->headScript();?>
    <!--[if lt IE 9]>  
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>  
    <![endif]-->  
    
    <!--FAVICONS-->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/img/favicon/favicon.ico');?>">
    <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon.png');?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon-72x72.png');?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl('/img/favicon/apple-touch-icon-114x114.png');?>">
    <!--END FAVICONS-->
    
</head>  
<body id="start_nicdark_framework">

<div class="nicdark_site">
    <div class="nicdark_site_fullwidth nicdark_clearfix">
        <div class="nicdark_overlay">
        </div>
    
    <div class="nicdark_section nicdark_navigation">
    
    <div class="nicdark_menu_boxed">

        <div class="nicdark_section nicdark_bg_greydark nicdark_displaynone_responsive">
            <div class="nicdark_container nicdark_clearfix">
                <div class="grid grid_6">
                    <div class="nicdark_focus">
                        <h6 class="white">
                            <i class="icon-calendar-outlilne"></i>&nbsp;&nbsp;<a class="white" href="">ДОГАЂАЈИ</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey">·</span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="icon-pencil-1"></i>&nbsp;&nbsp;<a class="white" href="<?= $this->url(array(), 'blognews', true);?>">НОВОСТИ</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey">·</span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="icon-phone-outline"></i>&nbsp;&nbsp;(065) 561-5054
                        </h6>
                    </div>
                </div>
                <div class="grid grid_6 right">
                    <div class="nicdark_focus right">
                        <h6 class="white">
                            <i class="icon-globe-alt-outline"></i>&nbsp;&nbsp;<a class="white nicdark_mpopup_window" href="#nicdark_window">ЈЕЗИЦИ</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey"></span>&nbsp;&nbsp;&nbsp;&nbsp;
                        </h6>
                    </div>
                </div>

                <!--info window for languages-->
                <div id="nicdark_window" class="nicdark_bg_white nicdark_radius zoom-anim-dialog mfp-hide">
                    
                    <div class="nicdark_textevidence nicdark_bg_red nicdark_radius_top">
                        <div class="nicdark_margin20">
                            <h4 class="white">ПРЕВОД</h4>
                        </div>
                    </div>

                    <div class="nicdark_margin20">
                        
                        <ul class="nicdark_list border">
                        
                            <li class="nicdark_border_grey">
                                <p><a class="grey" href="">ЋИРИЛИЦА</a><a class="nicdark_btn right nicdark_opacity"><img alt="" width="30" src="<?php echo $this->baseUrl('/img/flag/img2.png');?>"></a></p>
                                <div class="nicdark_space15"></div>
                            </li>

                            <li class="nicdark_border_grey">
                                <div class="nicdark_space15"></div>
                                <p><a class="grey" href="">LATINICA</a><a  class="nicdark_btn right nicdark_opacity"><img alt="" width="30" src="<?php echo $this->baseUrl('/img/flag/img3.png');?>"></a></p>   
                                <div class="nicdark_space15"></div>
                            </li>
                                
                            <li class="nicdark_border_grey">
                                <div class="nicdark_space15"></div>
                                <p><a class="grey" href="">ENGLISH</a><a  class="nicdark_btn right nicdark_opacity"><img alt="" width="30" src="<?php echo $this->baseUrl('/img/flag/img1.png');?>"></a></p>   
                                <div class="nicdark_space15"></div>
                            </li>
                        </ul>

                    </div>
                </div>
                <!--end window-->

            </div>
        </div>

        <div class="nicdark_space3 nicdark_bg_gradient"></div>
                    
        <div class="nicdark_section nicdark_bg_grey nicdark_shadow nicdark_radius_bottom fade-down">
            <div class="nicdark_container nicdark_clearfix">

                <div class="grid grid_12 percentage">
                        
                        <div class="nicdark_space20"></div>

                        <div class="nicdark_logo nicdark_marginleft10">
                            <a href="<?= $this->baseUrl('/');?>"><img alt="" src="<?= $this->baseUrl('img/logo.png');?>"></a>
                        </div>
                        
                        <nav>
                            <ul class="nicdark_menu nicdark_margin010 nicdark_padding50">

                                <li class="yellow">
                                    <a href="<?= $this->baseUrl('/') ?>">
                                        ПОЧЕТНА
                                    </a>
                                </li>
                                <li class="orange">
                                    <a href="<?= $this->url(array(), 'aboutschool', true);?>">О ШКОЛИЦИ</a>
                                </li>
                                <li class="orange">
                                    <a href="<?= $this->url(array(), 'organization', true);?>">О УДРУЖЕЊУ</a>
                                </li>

                                <li class="blue ">
                                    <a>НАСТАВА</a>
                                    <ul class="sub-menu">
                                        <li><a href="<?= $this->url(array(), 'workshopgroup', true);?>">ГРУПНА</a></li>
                                        <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">ИНДИВИДУАЛНА</a></li>
                                    </ul>
                                </li>
                                <li class="violet">
                                    <a href="<?= $this->url(array(), 'blognews', true);?>">НОВОСТИ</a>
                                </li>
                                <li class="grey">
                                    <a href="<?= $this->url(array(), 'contactpage', true);?>">КОНТАКТ</a>
                                </li>

                            </ul>
                        </nav>
    
                        <div class="nicdark_space20"></div>

                </div>

            </div>
            <!--end container-->

        </div>
        <!--end header-->

    </div>

</div>

</div>
<!-- Zend load content -->

<?php echo $this->layout()->content;?>

<!-- Zend end content loading -->

<div class="nicdark_space3 nicdark_bg_gradient"></div>

<!--start section-->
<section class="nicdark_section nicdark_bg_greydark">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space30"></div>

        <div class="grid grid_3 nomargin percentage">

            <div class="nicdark_space20"></div>

            <div class="nicdark_margin10">
                <h4 class="white">МАЛИ МОЦАРТ</h4>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left small"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space20"></div>
                <p class="white">М узички студио, или како га ми радије зовемо- ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“, отворен је са 
                    циље..</p>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left small"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space20"></div>
                <a href="contact-1.html" class="nicdark_btn_icon nicdark_bg_orange small nicdark_shadow nicdark_radius white"><i class="icon-mail-1 nicdark_rotate"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="contact-1.html" class="nicdark_btn_icon nicdark_bg_yellow small nicdark_shadow nicdark_radius white"><i class="icon-home nicdark_rotate"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="contact-1.html" class="nicdark_btn_icon nicdark_bg_red small nicdark_shadow nicdark_radius white"><i class="icon-phone-outline nicdark_rotate"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
        </div>

        <div class="grid grid_3 nomargin percentage">
            
            <div class="nicdark_space30"></div>

            <div class="nicdark_marginleft10">
                <h4 class="white">ОБЛАК ОЗНАКА</h4>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left small"><span class="nicdark_bg_white nicdark_radius"></span></div>
            </div>
            <div class="nicdark_space10"></div>

            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака1</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака2</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака3</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака4</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака5</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака6</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака7</a>
            <a href="#" class="nicdark_btn nicdark_bg_greydark2 small nicdark_shadow nicdark_radius white subtitle nicdark_margin10">Ознака8</a>
        </div>

        <div class="grid grid_3 nomargin percentage">

            <div class="nicdark_space20"></div>
            
            <div class="nicdark_margin10">
                <h4 class="white">МИНИ ГАЛЕРИЈА ШКОЛИЦЕ</h4>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left small"><span class="nicdark_bg_white nicdark_radius"></span></div>
            </div>
            

            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img1.jpg">
                </div>
            </div>
            
            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img2.jpg">
                </div>
            </div>
            
            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img3.jpg">
                </div>
            </div>
            
            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img4.jpg">
                </div>
            </div>
            
            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img5.jpg">
                </div>
            </div>
            
            <div class="grid nomargin grid_4 percentage">
                <div class="nicdark_margin10">
                    <img alt="" class="nicdark_radius nicdark_opacity nicdark_focus" src="img/footer/img6.jpg">
                </div>
            </div>
            

        </div>

        <div class="grid grid_3 nomargin percentage">

            <div class="nicdark_space20"></div>

            <div class="nicdark_margin10">
                <h4 class="white">КОНТАКТ ФОРМА</h4>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left small"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space20"></div>
                

                <input class="nicdark_bg_greydark2 nicdark_radius nicdark_shadow white small subtitle" type="text" value="" placeholder="И-МЕЈЛ">
                <div class="nicdark_space20"></div>
                <textarea rows="3" class="nicdark_bg_greydark2 nicdark_radius nicdark_shadow white small subtitle" placeholder="ПОРУКА"></textarea>
                <div class="nicdark_space20"></div>
                <!--<input class="nicdark_btn nicdark_bg_green small nicdark_shadow nicdark_radius white nicdark_press" type="submit" value="SEND">-->
                <a href="submit-message.html" class="nicdark_mpopup_ajax nicdark_btn nicdark_bg_green small nicdark_shadow nicdark_radius white nicdark_press">ПОШАЉИ</a>
            </div>
        </div> 

        <div class="nicdark_space50"></div> 

    </div>
    <!--end nicdark_container-->
            
</section>
<!--end section-->


<!--start section-->
<div class="nicdark_section nicdark_bg_greydark2 nicdark_copyrightlogo">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="grid grid_6 nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
            <div class="nicdark_space20"></div>
            <p class="white">СВА ПРАВА ЗАДРЖАНА - ШКОЛИЦА "МАЛИ МОЦАРТ" <i class="icon-heart-filled red nicdark_zoom"></i> БЕОГРАД</p>
        </div>


        <div class="grid grid_6">
            <div class="nicdark_focus right nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
                <div class="nicdark_margin10">
                    <a href="https://www.facebook.com/malimocart/" target="_blank"class="nicdark_facebook nicdark_press right nicdark_btn_icon small nicdark_radius white"><i class="icon-facebook-1"></i></a>
                </div>
                <div class="nicdark_margin10">
                    <a href="#" class="nicdark_press right nicdark_btn_icon nicdark_bg_red nicdark_shadow small nicdark_radius white"><i class="icon-gplus"></i></a>
                </div>
                <div class="nicdark_margin10">
                    <a href="#" class="nicdark_press right nicdark_btn_icon nicdark_bg_blue nicdark_shadow small nicdark_radius white"><i class="icon-twitter-1"></i></a>
                </div>
                <div class="nicdark_margin10">
                    <a href="#start_nicdark_framework" class="nicdark_zoom nicdark_internal_link right nicdark_btn_icon nicdark_bg_greydark2 small nicdark_radius white"><i class="icon-up-outline"></i></a>
                </div>
            </div>
        </div>

    </div>
    <!--end nicdark_container-->
            
</div>
<!--end section-->        </div>

    <!--main-->
    <script src="<?php echo $this->baseUrl('/js/main/jquery.min.js');?>"></script> <!--Jquery-->
    <script src="<?php echo $this->baseUrl('/js/main/jquery-ui.js');?>"></script> <!--Jquery UI-->
    <script src="<?php echo $this->baseUrl('/js/main/excanvas.js');?>"></script> <!--canvas need for ie-->

    <!--plugins-->
    <script src="<?php echo $this->baseUrl('/js/plugins/revslider/jquery.themepunch.tools.min.js');?>"></script> <!--revslider-->
    <script src="<?php echo $this->baseUrl('/js/plugins/revslider/jquery.themepunch.revolution.min.js');?>"></script> <!--revslider-->

    <!--menu-->
    <script src="<?php echo $this->baseUrl('/js/plugins/menu/superfish.min.js');?>"></script> <!--superfish-->
    <script src="<?php echo $this->baseUrl('/js/plugins/menu/tinynav.min.js');?>"></script> <!--tinynav-->

    <!--other-->
    <script src="<?php echo $this->baseUrl('/js/plugins/isotope/isotope.pkgd.min.js');?>"></script> <!--isotope-->
    <script src="<?php echo $this->baseUrl('/js/plugins/mpopup/jquery.magnific-popup.min.js');?>"></script> <!--mpopup-->
    <script src="<?php echo $this->baseUrl('/js/plugins/scroolto/scroolto.js');?>"></script> <!--Scrool To-->
    <script src="<?php echo $this->baseUrl('/js/plugins/nicescrool/jquery.nicescroll.min.js');?>"></script> <!--Nice Scroll-->
    <script src="<?php echo $this->baseUrl('/js/plugins/inview/jquery.inview.min.js');?>"></script> <!--inview-->
    <script src="<?php echo $this->baseUrl('/js/plugins/parallax/jquery.parallax-1.1.3.js');?>"></script> <!--parallax-->
    <script src="<?php echo $this->baseUrl('/js/plugins/countto/jquery.countTo.js');?>"></script> <!--jquery.countTo-->
    <script src="<?php echo $this->baseUrl('/js/plugins/countdown/jquery.countdown.js');?>"></script> <!--countdown-->
    
    <!-- Layer Slider --> 
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery-transit-modified.js');?>"></script> 
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/layerslider.kreaturamedia.jquery.js');?>"></script> 
    <script type='text/javascript' src="<?php echo $this->baseUrl('/js/greensock.js');?>"></script> 
    <script type='text/javascript' src="<?php echo $this->baseUrl('/js/layerslider.transitions.js');?>"></script> 
    <script type='text/javascript' src="<?php echo $this->baseUrl('/js/jquery.modal.js');?>"></script> 
    <script src="<?php echo $this->baseUrl('/js/settings.js');?>"></script> <!--settings-->
    <script type="text/javascript">var lsjQuery = jQuery;</script><script type="text/javascript"> lsjQuery(document).ready(function() { if(typeof lsjQuery.fn.layerSlider == "undefined") { lsShowNotice('layerslider_1','jquery'); } else { lsjQuery("#layerslider_4").layerSlider({responsiveUnder: 1170, layersContainer: 1170, skinsPath: 'js/layerslider/skins/'}) } }); </script>
    <!--custom js-->
    <style>
        @media only screen and (max-width: 767px) {
            #layerslider_4 {
                display:none !important;
                height: 0px;
            }
            .nicdark_section .nicdark_margintop45_negative {
                margin-top: -140px !important;
            }
            .nicdark_logo img {
                position: absolute;
                width: 200px;
                margin: 97px;
                margin-top: -15px;
                border: 0;
            }
        }
    </style>
    <?php echo $this->inlineScript();?>
<!--custom js-->
</body>  
</html>
