<section id="content_wrapper">
<header id="topbar" class="alt">
       <div class="topbar-left">
          <ol class="breadcrumb">
             <li class="breadcrumb-link">
                <a href="<?= $this->url(array('controller' => 'admin_dashboard', 'action' => 'index'), 'default', true);?>">CMS Почетна</a>
             </li>
             <li class="breadcrumb-link">
                <a>CMS Мејл</a>
             </li>
             <li class="breadcrumb-current-item">Све поруке</li>
          </ol>
       </div>
    </header>
<?= $this->iconNavigation();?>
<?= $this->systemMessagesHtml($this->systemMessages);?>
<section id="content" class="table-layout animated fadeIn">
   <aside class="chute chute-left chute-icon-style chute290 bg-info" data-chute-height="match">
      <div class="chute-icon"></div>
      <div class="chute-container">
         <button id="quick-compose" type="button" class="btn btn-dark light btn-block fw600">Нова порука
         </button>
         <div class="list-group list-group-links in-bg-chute mt20">
            <div class="list-group-header"> CMS Мејл</div>
            <a href="#" class="list-group-item">
            <i class="fa fa-envelope-o"></i>
            Пријемно сандуче
            <span class="label badge-warning">4</span>
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-save"></i>
            Недовршене
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-file-o"></i>
            Послате
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-times-circle-o"></i>
            Спам
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-trash-o"></i>
            Обрисане
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-spinner"></i>
            Мејл Подешавања
            </a>
            <a href="#" class="list-group-item">
            <i class="fa fa-smile-o"></i>
            Контакти
            <span class="label badge-dark">3</span>
            </a>
         </div>
      </div>
   </aside>
   <div class="chute chute-center pn bg-light">
      <div class="panel m20">
         <div class="panel-menu br-n pn mtn">
            <div class="row">
               <div class="hidden-xs hidden-sm col-md-3">
                  <div class="btn-group">
                     <button type="button" class="btn btn-default light text-dark">
                     <i class="fa fa-refresh"></i>
                     </button>
                     <button type="button" class="btn btn-default light text-dark">
                     <i class="fa fa-pencil"></i>
                     </button>
                  </div>
               </div>
               <div class="col-xs-12 col-md-9 text-right ta-l-xs">
                  <button type="button" class="btn btn-dark light visible-xs-inline-block mr10">
                  Compose
                  </button>
                  <span class="hidden-xs va-m text-muted mr15"> <strong>4</strong> нових порука
                  </span>
                  <div class="btn-group mr10">
                     <button type="button" class="btn btn-default light text-dark hidden-xs">
                     <i class="fa fa-star"></i>
                     </button>
                     <button type="button" class="btn btn-default light text-dark hidden-xs">
                     <i class="fa fa-calendar"></i>
                     </button>
                     <button type="button" class="btn btn-default light text-dark">
                     <i class="fa fa-trash"></i>
                     </button>
                  </div>
                  <div class="btn-group mr10">
                     <div class="btn-group">
                        <button type="button" class="btn btn-default light text-dark dropdown-toggle ph8" data-toggle="dropdown">
                        <span class="fa fa-tags"></span>
                        <span class="caret ml5"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                           <li>
                              <a href="#">Submenu #1</a>
                           </li>
                           <li>
                              <a href="#">Submenu #2</a>
                           </li>
                           <li>
                              <a href="#">Submenu #3</a>
                           </li>
                           <li class="divider"></li>
                           <li>
                              <a href="#">
                              <span class="fa fa-plus pr5"></span> Пошаљи поруку</a>
                           </li>
                        </ul>
                     </div>
                     <div class="btn-group">
                        <button type="button" class="btn btn-default light text-dark dropdown-toggle ph8 br-tp-left" data-toggle="dropdown">
                        <span class="fa fa-folder"></span>
                        <span class="caret ml5"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                           <li>
                              <a href="#">Submenu #1</a>
                           </li>
                           <li>
                              <a href="#">Submenu #2</a>
                           </li>
                           <li>
                              <a href="#">Submenu #3</a>
                           </li>
                           <li class="divider"></li>
                           <li>
                              <a href="#">
                              <span class="fa fa-plus pr5"></span> Пошаљи поруку</a>
                           </li>
                        </ul>
                     </div>
                  </div>
                  <div class="btn-group">
                     <button type="button" class="btn btn-default light text-dark">
                     <i class="fa fa-chevron-left"></i>
                     </button>
                     <button type="button" class="btn btn-default light text-dark">
                     <i class="fa fa-chevron-right"></i>
                     </button>
                  </div>
               </div>
            </div>
         </div>
         <div class="table-responsive">
            <table id="message-table" class="table tc-checkbox-1 allcp-form theme-warning br-t btn-gradient-grey">
               <thead>
                  <tr class="">
                     <th class="text-center hidden-xs">Означи</th>
                     <th class="hidden-xs">Битне</th>
                     <th>Пошиљаоц</th>
                     <th>Мејл</th>
                     <th class="hidden-xs">Порука</th>
                     <th class="text-center">Датум</th>
                  </tr>
               </thead>
               <tbody>
                  <tr class="message-unread">
                     <td class="hidden-xs">
                        <label class="option block mn">
                        <input type="checkbox" name="inputname" value="FR">
                        <span class="checkbox mn"></span>
                        </label>
                     </td>
                     <td class="hidden-xs">
                        <span class="rating block mn pull-left">
                        <input class="rating-input" id="r1" type="radio" name="custom">
                        <label class="rating-star" for="r1">
                        <i class="fa fa-star va-m"></i>
                        </label>
                        </span>
                     </td>
                     <td class="">Ђорђе Стојиљковић</td>
                     <td class="hidden-xs"></td>
                     <td class="">Нека порука која треба да је послата.</td>
                     <td class="text-center fw600">Септембар 29</td>
                  </tr>
               </tbody>
            </table>
         </div>
      </div>
   </div>
</section>
</section>
<!--<div class="quick-compose-form">
   <form>
      <input type="email" class="form-control" id="inputEmail" placeholder="Email">
      <input type="text" class="form-control" id="inputSubject" placeholder="Subject">
      <div class="summernote-quick">Compose your message here...</div>
   </form>
</div>-->
<?php $this->inlineScript()->captureStart();?>
        // Init Summernote
<!--        $('.summernote-quick').summernote({
            height: 275,
            focus: false,
            toolbar: [
                ['style', ['bold', 'italic', 'underline' ]],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']]
            ]
        });-->
$('#topbar-dropmenu-wrapper').removeAttr('style')
<?php $this->inlineScript()->captureEnd();?>
<?php $this->headStyle()->captureStart();?>
    #content .panel {
        padding: 28px 32px !important;
    }
    .topbar-dropmenu-open {
        display: none !important;
    }
<?php $this->headStyle()->captureEnd();?>