<div id="main">
        	<!--breadcrumb-section starts-->
            <div class="breadcrumb-section">
            	<div class="container">
                	<h1>О Нама </h1>
                    <div class="breadcrumb">
                        <a href="index.html">Почетна</a>
                        <span class="fa fa-angle-double-right"></span>
                        <span class="current">О Нама</span>
                    </div>
                </div>
            </div>
            <!--breadcrumb-section ends-->
            <!--container starts-->
            <div class="container">
            	<!--primary starts-->
            	<section id="primary" class="content-full-width">
                    <div class="column dt-sc-one-half first">
                        <img src="<?php echo $this->baseUrl('/images/activity1.jpg');?>" alt="" title="" 
                             style="float: left; list-style: none; position: relative; width: 572px;"> 
                    </div>
                    <div class="column dt-sc-one-half">                  
                    	<h3>Школица Мали Моцарт</h3>
                        <p style="text-align: justify; margin-top: -7px;">
                            <strong>Музички студио</strong>, или како га ми радије зовемо- ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА <b>„Мали Моцарт“</b>, 
                            отворен је са циљем да кроз занимљиве интерактивне садржаје и програме приближи и објасни музику и 
                            све њене пратеће компоненте, како најмлађима, тако и свима који би желели да своје знање оплемене и допуне.
                        </p>
                        <p style="text-align: justify;">
                            Како име каже, ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“ ради управо то- кроз игру, покрет, визуелизацију, 
                            цртање, плес и низ других активности, малишани активно учествују у радионицама, те упијају нове вештине, 
                            развијају своје ритмичке, моторичке и музичке способности, као и музички језик (ноте, динамика, темпо итд) на
                            један леп, неоптерећујући начин.
                        </p>
                        <p><b>Јер, најбољи начин учења је- КРОЗ ИГРУ!</b> </p>                      
                    </div>
                    
                    <div class="dt-sc-hr" style="margin-top: 0px;"></div>
                    <!--dt-sc-one-half starts-->
                    <div class="column dt-sc-one-half first">
                    	<h3>Настава се одвија на два начина:</h3>
                        <div class="dt-sc-toggle-frame-set">
                            <h5 class="dt-sc-toggle-accordion  active"><a href="#">Групна настава</a></h5>
                            <div class="dt-sc-toggle-content" style="display: block;">
                                <div class="block">
                                    Подразумева рад у малим групама, до 6 полазника. <br>
                                    У зависности од узраста, одржава се у две категорије... <a href="">Детаљније</a>
                                </div>
                            </div>
                            <h5 class="dt-sc-toggle-accordion "><a href="#">Индивидуална настава</a></h5>
                            <div class="dt-sc-toggle-content">
                                <div class="block">
                                    Подразумева рад наставника са сваким учеником појединачно. <br>
                                    Ми Вам нудимо следеће области: <a href="">Детаљније</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column dt-sc-one-half">
                        <img src="<?php echo $this->baseUrl('/images/activity2.jpg');?>" alt="" title="" 
                             style="float: left; list-style: none; position: relative; width: 572px;"> 
                    </div>
                    <!--dt-sc-one-half ends-->
                    <div class="dt-sc-hr"></div>
                </section>
                <!--primary ends-->
            </div>
            <!--container ends-->
        </div>
