<?php 
    $this->doctype('XHTML1_RDFA');
    $this->headMeta()->setProperty('og:title', 'O ШКОЛИЦИ MАЛИ МОЦАРТ');
    $this->headMeta()->setProperty('og:type', 'Новости');
    $this->headMeta()->setProperty('og:author', 'Ана');
?>
<section id="nicdark_parallax_countdown" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img-events" style="background-position: 50% -118px;">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="nicdark_space40"></div>
            <div class="nicdark_space50"></div>
            <div class="nicdark_space100"></div>

            <div class="grid grid_12">
                <h1 class="white center subtitle">О НАМА</h1>
                <div class="nicdark_space10"></div>
                <div class="nicdark_divider center big"><span class="nicdark_bg_white nicdark_radius"></span></div> 
                <div class="nicdark_space20"></div>    
            </div>
            <div class="nicdark_space40"></div>
        </div>
        <!--end nicdark_container-->
    </div>
</section>

<section class="nicdark_section">
    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space50"></div>

        <div class="grid grid_12">
            <h1 class="subtitle greydark">О НАМА</h1>
            <div class="nicdark_space20"></div>
            <h3 class="subtitle grey">ШКОЛИЦА "МАЛИ МОЦАРТ"</h3>
            <div class="nicdark_space20"></div>
            <div class="nicdark_divider left big"><span class="nicdark_bg_green nicdark_radius"></span></div>
            <div class="nicdark_space10"></div>
        </div>
        <div class="grid grid_4 nicdark_displaynone_ipadpotr nicdark_masonry_item">
            <img src="<?= $this->baseUrl('/img/activity1.jpg');?>" style="width: 100%;">
        </div>    
        <div class="grid grid_8 nicdark_displaynone_ipadpotr nicdark_masonry_item">
            <p style="text-align: justify; font-size: 16px;"><span class="red nicdark_dropcap nicdark_radius nicdark_shadow" style="font-size: 60px;">М</span>
                узички студио, или како га ми радије зовемо- <strong>ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“</strong>, отворен је са циљем 
                да кроз занимљиве интерактивне садржаје и програме приближи и објасни музику и све њене пратеће компоненте, 
                како најмлађима, тако и свима који би желели да своје знање оплемене и допуне.
                <br>
                Како име каже, <strong>ИГРАОНИЦА-РАДИОНИЦА-УЧИОНИЦА „Мали Моцарт“</strong> ради управо то- кроз игру, покрет, визуелизацију, 
                цртање, плес и низ других активности, малишани активно учествују у радионицама, те упијају нове вештине, 
                развијају своје ритмичке, моторичке и музичке способности, као и музички језик (ноте, динамика, темпо итд) 
                на један леп, неоптерећујући начин.
            </p>
        </div>
        <div class="nicdark_space20"></div>
        <div class="grid grid12">
            <div class="nicdark_alerts nicdark_bg_green nicdark_radius nicdark_shadow" style="text-align: center;">
                <h2 class="white nicdark_size_medium" >ЈЕР, НАЈБОЉИ НАЧИН УЧЕЊА ЈЕ - КРОЗ ИГРУ!</h2>
                <i class="icon-ok-outline nicdark_iconbg right medium green"></i>
            </div>
        </div>
        <div class="nicdark_space20"></div>
        <div class="nicdark_space20"></div>
        <div class="grid grid_8 nicdark_displaynone_ipadpotr nicdark_masonry_item">
            <h3 class="subtitle grey">НАСТАВА СЕ ОДВИЈА НА ДВА НАЧИНА:</h3>
            <div class="nicdark_space20"></div>
            <div class="nicdark_divider left small"><span class="nicdark_bg_orange nicdark_radius"></span></div>
            <div class="nicdark_space20"></div>

            <div class="nicdark_accordion ui-accordion ui-widget ui-helper-reset" role="tablist">
                <h5 class="nicdark_accordion_header white big nicdark_bg_blue nicdark_shadow nicdark_radius ui-accordion-header ui-helper-reset ui-state-default ui-accordion-icons ui-accordion-header-active ui-state-active ui-corner-top" role="tab" id="ui-accordion-3-header-0" aria-controls="ui-accordion-3-panel-0" aria-selected="true" tabindex="0">
                    <span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-s"></span>ГРУПНА НАСТАВА</h5>
                <div class="nicdark_accordion_content ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active" id="ui-accordion-3-panel-0" aria-labelledby="ui-accordion-3-header-0" role="tabpanel" aria-expanded="true" aria-hidden="false" style="display: block;">
                    <p>Подразумева рад у малим групама, до 6 полазника. 
                        У зависности од узраста, одржава се у три категорије:</p>
                        <ul>
                            <li><a href="<?= $this->url(array(), 'workshopgroup', true);?>">Радионице</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopgroup', true);?>">Мали оркестар</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopgroup', true);?>">Мали хорић</a></li>
                        </ul>
                </div>

                <h5 class="nicdark_accordion_header white big nicdark_bg_blue nicdark_shadow nicdark_radius ui-accordion-header ui-helper-reset ui-state-default ui-accordion-icons ui-corner-all" role="tab" id="ui-accordion-3-header-1" aria-controls="ui-accordion-3-panel-1" aria-selected="false" tabindex="-1">
                    <span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e"></span>ИНДИВИДУАЛНА НАСТАВА</h5>
                <div class="nicdark_accordion_content ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-accordion-3-panel-1" aria-labelledby="ui-accordion-3-header-1" role="tabpanel" aria-expanded="false" aria-hidden="true" style="display: none;">
                    <p>Индивидуална настава подразумева рад наставника са сваким учеником појединачно. 
                        <br>Ми Вам нудимо следеће области: </p>
                        <ul>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Клавир</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Солфеђо</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Соло певање</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Популарна и џез музика</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Увод у компоновање</a></li>
                            <li><a href="<?= $this->url(array(), 'workshopindividual', true);?>">Основе теорије музике</a></li>
                        </ul>
                </div>

            </div>
        </div>
        <div class="grid grid_4 nicdark_displaynone_ipadpotr nicdark_masonry_item">
            <div class="nicdark_space60" style="padding-top: 3px;"></div>
            <img src="<?= $this->baseUrl('/img/activity2.png');?>" style="width: 60%;">
        </div>   
   </div>
   <!--end nicdark_container-->
            
</section>