<!--start section-->
<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img5">
    <div class="nicdark_filter greydark">
        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">
            <div class="grid grid_12">
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">О УДРУЖЕЊУ</h1>
                <div class="nicdark_space100"></div>
            </div>
        </div>
        <!--end nicdark_container-->
    </div>
</section>
<!--end section-->

<!--start section-->
<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space40"></div>

        <div class="grid grid_6">
            <!--title-->
            <h3 class="subtitle greydark">О УДРУЖЕЊУ</h3>
            <div class="nicdark_space20"></div>
            <div class="nicdark_divider left small"><span class="nicdark_bg_yellow nicdark_radius"></span></div>
            <!--title--> 
            
            <div class="nicdark_space20"></div>
            <p style="text-align: justify;">
                Удружење за културно-уметнички израз младих „Ихос“ (у даљем тексту:

Удружење) је добровољно, невладино и нестраначко удружење, основано на

неодређено време ради остваривања циљева у области културног и уметничког

стваралаштва.
            </p>

        </div>
        
       <div class="grid grid_6">
                <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                    <div class="nicdark_textevidence nicdark_bg_red nicdark_radius_top">
                        <h4 class="white nicdark_margin20">СТАТУТ УДРУЖЕЊА</h4>
                        <i class="icon-download-outline nicdark_iconbg right medium red"></i>
                    </div>
                    <ul class="nicdark_list border">
                        <li class="nicdark_border_grey">
                            <div class="nicdark_margin20 nicdark_relative">
                            <a href="<?= $this->url(array('controller' => 'about', 'action' => 'status'),'default',true);?>" target="_blank" class="nicdark_btn_icon small nicdark_radius_circle red nicdark_absolute nicdark_border_red"><i class="icon-file-pdf"></i></a>
                                <div class="nicdark_space10"></div>
                                <div class="nicdark_activity nicdark_marginleft60">
                                    <a href="<?= $this->url(array('controller' => 'about', 'action' => 'status'),'default',true);?>" target=""><h5 class="blue">ПОГЛЕДАЈ СТАТУТ УДРУЖЕЊА</h5></a>
                                </div>
                            </div>
                            <div class="nicdark_margin20 nicdark_relative">
                            <a href="http://malimocart.rs/uploads/dokumenti/mali-mocart-skolica-statut.doc" class="nicdark_btn_icon small nicdark_radius_circle red nicdark_absolute nicdark_border_red"><i class="icon-file-pdf"></i></a>
                                <div class="nicdark_space10"></div>
                                <div class="nicdark_activity nicdark_marginleft60">
                                    <a href="http://malimocart.rs/uploads/dokumenti/mali-mocart-skolica-statut.doc"><h5 class="blue">ПРЕУЗМИ СТАТУТ УДРУЖЕЊА</h5></a>                         
                                    <div class="nicdark_space10"></div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
        </div>
    </div>
    <!--end nicdark_container-->
    <div class="nicdark_space50"></div>
</section>
<!--end section-->