<?php
$this->headTitle('Контакт');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
?>
<!--start section-->
<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img5">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space50"></div>
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">КОНТАКТ</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">СЛОБОДНО НАС КОНТАКТИРАЈТЕ!</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space40"></div>
                <div class="nicdark_space50"></div>
            </div>

        </div>
        <!--end nicdark_container-->

    </div>
     
</section>
<!--end section-->


<!--start section-->
<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space40"></div>


        <div class="grid grid_4">

            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                <div class="nicdark_margin20 nicdark_relative">
                        <a href="#" class="nicdark_displaynone_ipadpotr nicdark_btn_icon nicdark_bg_yellow extrabig nicdark_radius_circle white nicdark_absolute nicdark_shadow"><i class="icon-location-outline nicdark_rotate"></i></a>
                        <div class="nicdark_activity nicdark_marginleft100 nicdark_disable_marginleft_ipadpotr">
                            <h4>АДРЕСА</h4>                        
                            <div class="nicdark_space20"></div>
                            <p>ГАНДИЈЕВА 114, ПИРАМИДА-КОЦКИЦА
                                НОВИ БЕОГРАД</p>
                        </div>
                </div>
            </div>

            <div class="nicdark_space20"></div>


            <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                <div class="nicdark_margin20 nicdark_relative">
                        <a href="#" class="nicdark_displaynone_ipadpotr nicdark_btn_icon nicdark_bg_orange extrabig nicdark_radius_circle white nicdark_absolute nicdark_shadow"><i class="icon-address nicdark_rotate"></i></a>
                        <div class="nicdark_activity nicdark_marginleft100 nicdark_disable_marginleft_ipadpotr">
                            <h4>ТЕЛЕФОН:</h4>                        
                            <div class="nicdark_space20"></div>
                            <p>(065) 561-5054<br><br></p>
                        </div>
                </div>
            </div>

            <div class="nicdark_space20"></div>


            <div class="nicdark_archive1 nicdark_bg_greydark nicdark_radius nicdark_shadow">
                <div class="nicdark_margin20 nicdark_relative">
                        <a href="#" class="nicdark_displaynone_ipadpotr nicdark_btn_icon nicdark_bg_red extrabig nicdark_radius_circle white nicdark_absolute nicdark_shadow"><i class="icon-paper-plane-empty nicdark_rotate"></i></a>
                        <div class="nicdark_activity nicdark_marginleft100 nicdark_disable_marginleft_ipadpotr">
                            <h4 class="white">И-МЕЈЛ</h4>                        
                            <div class="nicdark_space20"></div>
                            <p class="white">info@malimocart.rs<br/>prijava@malimocart.rs</p>
                        </div>
                </div>
            </div>

        
        </div>

        <?php
        $userIp = Zend_Controller_Front::getInstance()->getRequest()->getServer('REMOTE_ADDR');
        $userAgent = new Zend_Http_UserAgent();
        $userBrowser    = $userAgent->getUserAgent();
        ;?>
        <form method="POST" action="">
        <input type="hidden" name="task" value="contact">
        <input type="hidden" name="ip" value="<?= $userIp;?>">
        <input type="hidden" name="useragent" value="<?= $userBrowser;?>">
        <input type="hidden" name="date_sended" value="not-empty">
            <div class="grid grid_8">
               <div class="nicdark_archive1 nicdark_bg_grey nicdark_radius nicdark_shadow">
                    <div class="nicdark_textevidence nicdark_bg_orange nicdark_radius_top">
                        <h4 class="white nicdark_margin20">КОНТАКТ ФОРМА</h4>
                        <i class="icon-mail nicdark_iconbg right medium orange"></i>
                    </div>
                    <div class="nicdark_margin20">
                        <?= 
                        $form->getElement('from_name')->setAttribs(array(
                        'class' => 'nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle',
                        'placeholder' => 'ВАШЕ ИМЕ',
                        'id' => 'usr',
                        'required' => 'required'
                        ));
                        ?>
                        <div class="nicdark_space20"></div>
                        <?= 
                        $form->getElement('from_email')->setAttribs(array(
                        'class' => 'nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle',
                        'placeholder' => 'И-МЕЈЛ',
                        'id' => 'usr',
                        'required' => 'required'
                        ));
                        ?>
                        <div class="nicdark_space20"></div>
                        <?= 
                        $form->getElement('message_text')->setAttribs(array(
                        'class' => 'nicdark_bg_grey2 nicdark_radius nicdark_shadow grey small subtitle',
                        'placeholder' => 'ВАША ПОРУКА',
                        'id' => 'usr',
                        'required' => 'required',
                        'rows' => 7
                        ));
                        ?>
                        <div class="nicdark_space20"></div>
                        <button type="submit" class="nicdark_btn nicdark_bg_orange medium nicdark_shadow nicdark_radius white nicdark_press">ПОШАЉИ</button>
                    </div>
                </div>
            </div>
        </form>
        <div class="nicdark_space50"></div>
    </div>
    <!--end nicdark_container-->
            
</section>
<!--end section-->

<!--start section-->
<section class="nicdark_section">
	<div class="nicdark_textevidence">
    	<iframe class="nicdark_iframe nicdark_margintop40_negative nicdark_marginbottom90_negative" src="https://mapsengine.google.com/map/embed?mid=1XmEk4Ir6lmgPYKom2Gl6ybjshNs&z=18" height="400" ></iframe>
	</div>
</section>
<!--end section-->