<div id="main">
        	<!--breadcrumb-section starts-->
            <div class="breadcrumb-section">
            	<div class="container">
                	<h1>Контакт</h1>
                    <div class="breadcrumb">
                        <a href="<?= $this->baseUrl('/') ;?>">Почетна</a>
                        <span class="fa fa-angle-double-right"></span>
                        <span class="current">Контакт</span>
                    </div>
                </div>
            </div>
            <!--breadcrumb-section ends-->
            <!--container starts-->
            <div class="container">
            	<!--primary starts-->
            	<section id="primary" class="content-full-width">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d707.7447374248052!2d20.38774234092276!3d44.801617635581714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd2fd14ce63745319!2z0JzQsNC70LAg0J_QuNGA0LDQvNC40LTQsA!5e0!3m2!1sen!2s!4v1471487096642" width="1170" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
                    <div class="dt-sc-hr"> </div>
                    
                    <!--dt-sc-two-third starts-->
                    <div class="column dt-sc-three-fourth first contact_form_outer">
                        <form name="frcontact" class="contact-form" method="post" action="">
                        	<h2>Пошаљите нам поруку!</h2>
                            <p class="column dt-sc-one-third first">
                                <input id="name" name="txtname" type="text" placeholder="Име" required="">
                            </p>
                            <p class="column dt-sc-one-third">
                                <input id="email" name="txtemail" type="email" placeholder="И-Мејл адреса" required="">
                            </p>
                            <p class="column dt-sc-one-third">
                            	<input id="subject" name="txtsubject" type="text" placeholder="Наслов" required="">
                            </p>
                            <p>
                            	<textarea id="comment" name="txtmessage" placeholder="Порука"></textarea>
                            </p>
                            <div id="ajax_contact_msg"> </div>
                            <p>
                                <input name="submit" type="submit" id="submit" class="dt-sc-button medium" value="Пошаљи">
                            </p>
                        </form>
                    </div>
                    <!--dt-sc-two-third ends-->
                    
                    <!--dt-sc-one-third starts-->
                    <div class="column dt-sc-one-fourth class_hours">
                    	<h2>Радно време</h2>
                        <ul class="class_hours">
                        	<li>Понедељак<span>9 - 15h</span></li>
                            <li>Уторак<span>9 - 15h</span></li>
                            <li>Среда<span>9 - 15h</span></li>
                            <li>Четвртак<span>9 - 15h</span></li>
                            <li>Петак<span>9 - 15h</span></li>
                            <li>Субота<span>Затворено</span></li>
                            <li>Недеља<span>Затворено</span></li>
                        </ul>
                        <div class="dt-sc-hr-small"></div>
                        <p><strong><span class="highlighter">Мали моцарт</span> и на мрежама.</strong></p>
                        <ul class="dt-sc-social-icons">
                        	<li class="facebook"><a href="#" class="dt-sc-tooltip-bottom"><img src="images/facebook.png" alt="" title=""></a></li>
                            <li class="twitter"><a href="#" class="dt-sc-tooltip-bottom"><img src="images/twitter.png" alt="" title=""></a></li>
                            <li class="gplus"><a href="#" class="dt-sc-tooltip-bottom"><img src="images/gplus.png" alt="" title=""></a></li>
                            <li class="pinterest"><a href="#" class="dt-sc-tooltip-bottom"><img src="images/pinterest.png" alt="" title=""></a></li>
                        </ul>
                    </div>
                    <!--dt-sc-one-third ends-->
                </section>
                <!--primary ends-->
            </div>
            <!--container ends-->
        </div>
<div class="dt-sc-hr"></div>
