<!--start section-->
<section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img7">

    <div class="nicdark_filter greydark">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="grid grid_12">
                <div class="nicdark_space60"></div>
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <h1 class="white subtitle">БЛОГ</h1>
                <div class="nicdark_space10"></div>
                <h3 class="subtitle white">НАЈНОВИЈЕ ОБЈАВЕ</h3>
                <div class="nicdark_space20"></div>
                <div class="nicdark_divider left big"><span class="nicdark_bg_white nicdark_radius"></span></div>
                <div class="nicdark_space40"></div>
                <div class="nicdark_space50"></div>
            </div>

        </div>
        <!--end nicdark_container-->

    </div>
     
</section>
<!--end section-->


<!--start section-->
<section class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">


        <div class="nicdark_space50"></div>

        
        <div class="nicdark_masonry_btns">
            <div class="nicdark_margin10">
                <a data-filter="*" class="nicdark_bg_grey2_hover nicdark_transition nicdark_btn nicdark_bg_grey small nicdark_shadow nicdark_radius grey">СВЕ</a>
            </div>
            <div class="nicdark_margin10">
                <a data-filter=".category_general" class="nicdark_bg_grey2_hover nicdark_transition nicdark_btn nicdark_bg_grey small nicdark_shadow nicdark_radius grey">ОПШТЕ</a>
            </div>
            <div class="nicdark_margin10">
                <a data-filter=".category_news" class="nicdark_bg_grey2_hover nicdark_transition nicdark_btn nicdark_bg_grey small nicdark_shadow nicdark_radius grey">НАЈАВЕ</a>
            </div>
            <div class="nicdark_margin10">
                <a data-filter=".category_announcements" class="nicdark_bg_grey2_hover nicdark_transition nicdark_btn nicdark_bg_grey small nicdark_shadow nicdark_radius grey">НОВОСТИ</a>
            </div>
            <div class="nicdark_space10"></div>
        </div>


        <!--start nicdark_masonry_container-->
        <div class="nicdark_masonry_container">

            <?php foreach ($this->posts as $post):?>
                <div class="grid grid_4 nicdark_masonry_item <?= $post['category_general'];?>">
                    <div class="nicdark_archive1 nicdark_bg_blue nicdark_radius nicdark_shadow">
                        
                        <img alt=""  src="/uploads/blog-photos/<?= $post['id'];?>.jpg">
                        <div class="nicdark_margin20">
                            <h4 class="white"><?= $post['title'];?></h4>
                            <div class="nicdark_space20"></div>
                            <div class="nicdark_space20"></div>
                            <p class="white" style="color: #fff !important;">
                                <?php echo (mb_strlen(strip_tags($post['text'])) > 160 ? mb_substr(strip_tags($post['text']), 0, 160) . "..." : strip_tags($post['text'])); ?>
                            </p>
                            <div class="nicdark_space20"></div>
                            <a href="<?= $this->url(array('controller' => 'blog', 'action' => 'details', 'id' => $post['id']),'default',true);?>" class="white nicdark_btn"><i class="icon-doc-text-1 "></i> Детаљније</a>                        
                        </div>

                        <i class="icon-doc-text-1 nicdark_iconbg right medium blue"></i>

                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <!--end nicdark_masonry_container-->

    </div>
    <!--end nicdark_container-->
            
</section>
<!--end section-->






<!--start section-->
<div class="nicdark_section">

    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space40"></div>

        <div class="grid grid_6 nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
            <a class="nicdark_disable_floatright_iphoneland nicdark_disable_floatright_iphonepotr nicdark_btn nicdark_bg_green medium right nicdark_shadow nicdark_radius white nicdark_press"><i class="icon-left-open-outline"></i>&nbsp;&nbsp;&nbsp;ПРЕТХОДНА</a>
        </div>
        <div class="grid grid_6 nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
            <a class=" nicdark_btn nicdark_bg_green medium nicdark_shadow nicdark_radius white nicdark_press">СЛЕДЕЋА&nbsp;&nbsp;&nbsp;<i class="icon-right-open-outline"></i></a>
        </div>

        <div class="nicdark_space50"></div>

    </div>
    <!--end nicdark_container-->
            
</div>
<!--end section-->