<div id="main">
        	<!--breadcrumb-section starts-->
            <div class="breadcrumb-section">
            	<div class="container">
                	<h1>Новости</h1>
                    <div class="breadcrumb">
                        <a href="<?= $this->baseUrl('/') ;?>">Почетна</a>
                        <span class="fa fa-angle-double-right"></span>
                        <span class="current">Новости</span>
                    </div>
                </div>
            </div>
            <!--breadcrumb-section ends-->
            <!--container starts-->
            <div class="container">
            	<!--primary starts-->
            	<section id="primary" class="with-sidebar">
                 
                	<div class="dt-sc-one-column">
                    	<article class="blog-entry">
                            <div class="blog-entry-inner">
                                <div class="entry-meta">
                                    <a href="blog-detail.html" class="blog-author"><img src="images/rounded-bg-img.jpg" alt="" title=""></a>
                                    <div class="date">
                                        <span> 27 </span> 
                                        <p> Авг <br> 2016 </p> 
                                    </div>
                                    <a href="#" class="entry_format"><span class="fa fa-picture-o"></span></a>	
                                </div>		
                                <div class="entry-thumb">
                                    <a href="blog-detail.html"><img src="images/blog_img1.jpg" alt="" title=""></a>
                                </div>		
                                <div class="entry-details">	
                                    <div class="entry-title">
                                        <h3><a href="blog-detail.html"> Наслов 1 </a></h3>
                                    </div>			
                                    <!--entry-metadata ends-->	
                                    <div class="entry-body">
                                        <p>Неки текст.</p>
                                    </div>	 		
                                    <a href="blog-detail.html" class="dt-sc-button small"> Детаљније <span class="fa fa-chevron-circle-right"> </span></a>		
                                </div>	
                            </div>
                        </article>
                	</div>
                    
                        <div class="dt-sc-one-column">
                    	<article class="blog-entry">
                            <div class="blog-entry-inner">
                                <div class="entry-meta">
                                    <a href="blog-detail.html" class="blog-author"><img src="images/rounded-bg-img.jpg" alt="" title=""></a>
                                    <div class="date">
                                        <span> 16 </span> 
                                        <p> Авг <br> 2016 </p> 
                                    </div>
                                    <a href="#" class="entry_format"><span class="fa fa-picture-o"></span></a>	
                                </div>		
                                <div class="entry-thumb">
                                    <a href="blog-detail.html"><img src="images/blog_img3.jpg" alt="" title=""></a>
                                </div>		
                                <div class="entry-details">	
                                    <div class="entry-title">
                                        <h3><a href="blog-detail.html"> Наслов 2 </a></h3>
                                    </div>			
                                    <!--entry-metadata ends-->	
                                    <div class="entry-body">
                                        <p>Неки текст.</p>                                    
                                    </div>	 		
                                    <a href="blog-detail.html" class="dt-sc-button small"> Детаљније <span class="fa fa-chevron-circle-right"> </span></a>		
                                </div>	
                            </div>
                        </article>
                	</div>
                </section>
                <!--primary ends-->
                
                <!--secondary starts-->
                <section id="secondary">
                
                	<aside class="widget widget_categories">
                    	<h3 class="widgettitle">Категорије</h3>
                        <ul>
                        	<li>
                            	<a href="#">Play School<span>(16)</span></a>
                            </li>
                            <li>
                            	<a href="#">Academic Performance<span>(3)</span></a>
                            </li>
                            <li>
                            	<a href="#">Co-curricular<span>(26)</span></a>
                            </li>
                            <li>
                            	<a href="#">Visual Education<span>(18)</span></a>
                            </li>
                            <li>
                            	<a href="#">Inter Competition<span>(4)</span></a>
                            </li>
                        </ul>
                    </aside>
                	
                    <aside class="widget widget_text">
                        <h3 class="widgettitle">Школица Текст</h3>
                        <p>In lobortis rhoncus pulvinar. Pellentesque habitant morbi tristique <a href="#" class="highlighter">senectus</a> et netus et malesuada fames ac turpis egestas. </p>
                        <p>Sed tempus ligula ac mi iaculis lobortis. Nam consectetur justo non nisi dapibus, ac commodo mi sagittis. Integer enim odio.</p>
					</aside>
                    
                    <aside class="widget widget_text">
                    	<h3 class="widgettitle">Школица Видео</h3>
                        <p>Our methods of teaching and level of quality instructors all add up to a well-rounded experience.</p>
                    	<iframe src="http://player.vimeo.com/video/21195297" width="420" height="200"></iframe>
                    </aside>
                    
                    <aside class="widget widget_tag_cloud">
                    	<h3 class="widgettitle">Ознаке</h3>
                        <div class="tagcloud">
                        	<a href="#">Звук</a>
                            <a href="#">Музика</a>
                            <a href="#">Деца</a>
                            <a href="#">Ноте</a>
                            <a href="#">Хор</a>
                            <a href="#">Мелодија</a>
                            <a href="#">Ритам</a>
                            <a href="#">Солфеђо</a>
                            <a href="#">Савладано</a>
                            <a href="#">Оркестар</a>
                        </div>
                    </aside>
                    
                </section>
                <!--secondary ends-->
                
            </div>
            <!--container ends-->
        </div>